default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: colors_development

test:
  <<: *default
  database: colors_test

production:
  <<: *default
  database: colors_production
